config/routes.rb
Roommateme::Application.routes.draw do  # 
	# Logged in
  # 
  constraints lambda { |req| !req.session[:user_id].blank? } do
    resources :users do
      resources :friends
    end    
    
    # Match route
    get 'matches' => "matches#index", :as => "matching"
    
    # Survey routes
    scope 'survey' do
      get '/' => "survey_responses#new", as: "take_survey"
      post 'submit' => "survey_responses#create", :as => "submit_survey"
      # get '/answers' => "survey_responses#show", :as => "view_survey"
    end
    
    # Messaging routes
    resources :messages, :only => [:new, :create, :show, :index] do
      get "/mark_as_read" => "messages#mark_as_read", :on => :member
      get "/mark_as_unread" => "messages#mark_as_unread", :on => :member
      get "/to/:to_id" => "messages#new", :as => "new_message", :on => :collection
		  post "/to/:to_id/create" => "messages#create", :as => "create_message", :on => :collection
		  post "/respond" => "messages#respond", :as => "respond_message", :on => :member
    end
	  
    # Search routes
    get "/search" => "search#search", :as => "search"
	  
    # Inventory routes
	  scope "/inventory" do
	    get '/' => "users#items", :as => :inventory
      get "/have/:item_id" => "users#have_item", :as => "inventory_have"
      get "/want/:item_id" => "users#want_item", :as => "inventory_want"
      delete "/have/:item_id" => "users#delete_have_item", :as => "inventory_have_delete"
      delete "/want/:item_id" => "users#delete_want_item", :as => "inventory_want_delete"
      get "/:category" => "item_categories#show", :as => :item_categories
    end
    
    # Community routes
    get "/community" => "community#index", :as => :community
    resources :affiliates, :only => [:index, :show] do
      get "/category/:category" => "affiliate_categories#show", :on => :collection, :as => :category
    end
    resources :community_partners, :only => [:index, :show] do
      get "/category/:category" => "community_partner_categories#show", :on => :collection, :as => :category
    end
    resources :tutors, :only => [:index, :show] do
      get "/category/:category" => "tutor_categories#show", :on => :collection, :as => :category
    end
    
    # Root route
	  root :to => "users#show", :as => "dashboard"
  end
  
  # browse route
  get 'browse' => "browse#index", :as => "browse"

  # 
  # Not logged in
  # 
  resources :universities, :only => [:index, :show]
  post "/users" => "users#create"
  
  # Session routes
  resources :sessions, :only => [:new, :create, :destroy]
  get "sign_out" => "sessions#destroy", :as => "log_out"
  get "sign_in" => "sessions#new", :as => "log_in"
  
  # Static routes
  get "about" => "static#about", :as => "about"
  get "terms" => "static#tos", :as => "terms"
  
  # Password reset and recovery routes
  # get "register" => "users#new", :as => "register"
  get "register" => "signup#new", :as => "register"
  post "register" => "signup#create", :as => "signup"
	get "recovery" => "users#recovery", :as => "recovery"
	post "send_recovery" => "users#send_recovery", :as => "send_recovery"
	get "reset/:token" => "users#reset_form", :as => "reset_form"
	put "reset" => "users#reset_password", :as => "reset_password"
	get "activate/:token" => "users#activate", :as => "activate"
	
  # Newsletter subscribe path
  post "subscribe" => "static#subscribe", :as => "subscribe"
  
  # Feedback routes
  post "feedback" => "feedbacks#create", :as => "feedbacks"
  get "flag/:id" => "feedbacks#flag", :as => "flag_user"
    
  # Admin routes
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Root route
  root :to => "static#landing"
  resources :community_partner_suggestions
  
  # Catch-all route
  # If you're not logged in, then none of the routes in the constraints block
  # will be defined (Rails 404s), so if you're trying to access one of those pages,
  # this will pick up and redirect you to sign in instead of just throwing a 404.
  match '*path' => redirect('/sign_in'), via: [:get, :post], :constraints => lambda { |req| req.session[:user_id].blank? }
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
  
  validates :name, :presence => true
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  
  def show
    if params[:category].present?
      @item_category = ItemCategory.find_by_name(params[:category])
      if params[:id].present?
        @affiliate = Affiliate.find(params[:id])
        if @affiliate.present?
          @items = @affiliate.items.where("item_category_id = ?", @item_category.id).order("name desc")
        else
          redirect_to inventory_path, :notice => "Could not find that affiliate."
        end
      else
        @items = @item_category.items.order("name desc")
      end
    else
      redirect_to inventory_path, :notice => "That category does not exist."
    end
  end

end

app/views/item_categories/show.html.erb
<div class="page">
  <section class="page-breadcrumb">
    <div class="container container-w80">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page"><a href="/inventory">Inventory</a></li>
          <li class="breadcrumb-item active" aria-current="page"><%= @item_category.name %></li>
        </ol>
      </nav>
    </div>
  </section>
  <section class="page-banner">
    <div class="container container-w80">
      <div class="page-heading">
        <h2><%= @item_category.name %></h2>
      </div>
    </div>
  </section>
  <section class="matches inventory-item">
    <div class="container-w80 container">
      <div class="matches-header">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-sm-12 col-12">
            <div class="heading">
              <h4>Total <%= pluralize(@items.count , "total item") %> in this category</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
      	<% @items.each do |item| %>
	        <div class="col-lg-6 col-md-12 col-sm-12 col-12">
	          <div class="card">
	            <div class="row">
	              <div class="col-lg-4 col-md-4 col-sm-12 col-12">
	                <div class="img-wrapper">
	                  <%= image_tag item.image_url(:big), class: "img-fluid" %>
	                </div>
	              </div>
	              <div class="col-lg-8 col-md-8 col-sm-12 col-12">
	                <div class="desc">
	                  <h5><%= item.name %></h5>
	                  <p><%= item.description %></p>
	                  <div class="button-wrapper">
	                  	<% if current_user.inventory_items.exists?(:item_id => item.id, :have => true) %>
	                  		<%= link_to "Delete from your inventory", inventory_have_delete_path(item), :confirm => "Are you sure you want to remove this as an item you own?", :class => "btn btn-primary", :method => :delete %>
                  		<% elsif current_user.inventory_items.exists?(:item_id => item.id, :want => true) %>
                  			<%= link_to "Delete from your inventory", inventory_want_delete_path(item), :confirm => "Are you sure you want to remove this as an item you own?", :class => "btn btn-primary", :method => :delete %>
	                  	<% else %>
		                    <div class="main-btn">
		                      <%= link_to "have it", inventory_have_path(item), :method => :get, :class => "btn btn-primary" %>
		                    </div>
		                    <div class="main-btn">
		                      <%= link_to "want it", inventory_want_path(item), :method => :get, :class => "btn btn-primary" %>
		                    </div>
	                    <% end %>
	                  </div>
	                </div>
	              </div>
	            </div>
	          </div>
	        </div>
        <% end %>
      </div>
    </div>
  </section>
</div>