config/routes.rb
Roommateme::Application.routes.draw do  # 
	# Logged in
  # 
  constraints lambda { |req| !req.session[:user_id].blank? } do
    resources :users do
      resources :friends
    end    
    
    # Match route
    get 'matches' => "matches#index", :as => "matching"
    
    # Survey routes
    scope 'survey' do
      get '/' => "survey_responses#new", as: "take_survey"
      post 'submit' => "survey_responses#create", :as => "submit_survey"
      # get '/answers' => "survey_responses#show", :as => "view_survey"
    end
    
    # Messaging routes
    resources :messages, :only => [:new, :create, :show, :index] do
      get "/mark_as_read" => "messages#mark_as_read", :on => :member
      get "/mark_as_unread" => "messages#mark_as_unread", :on => :member
      get "/to/:to_id" => "messages#new", :as => "new_message", :on => :collection
		  post "/to/:to_id/create" => "messages#create", :as => "create_message", :on => :collection
		  post "/respond" => "messages#respond", :as => "respond_message", :on => :member
    end
	  
    # Search routes
    get "/search" => "search#search", :as => "search"
	  
    # Inventory routes
	  scope "/inventory" do
	    get '/' => "users#items", :as => :inventory
      get "/have/:item_id" => "users#have_item", :as => "inventory_have"
      get "/want/:item_id" => "users#want_item", :as => "inventory_want"
      delete "/have/:item_id" => "users#delete_have_item", :as => "inventory_have_delete"
      delete "/want/:item_id" => "users#delete_want_item", :as => "inventory_want_delete"
      get "/:category" => "item_categories#show", :as => :item_categories
    end
    
    # Community routes
    get "/community" => "community#index", :as => :community
    resources :affiliates, :only => [:index, :show] do
      get "/category/:category" => "affiliate_categories#show", :on => :collection, :as => :category
    end
    resources :community_partners, :only => [:index, :show] do
      get "/category/:category" => "community_partner_categories#show", :on => :collection, :as => :category
    end
    resources :tutors, :only => [:index, :show] do
      get "/category/:category" => "tutor_categories#show", :on => :collection, :as => :category
    end
    
    # Root route
	  root :to => "users#show", :as => "dashboard"
  end
  
  # browse route
  get 'browse' => "browse#index", :as => "browse"

  # 
  # Not logged in
  # 
  resources :universities, :only => [:index, :show]
  post "/users" => "users#create"
  
  # Session routes
  resources :sessions, :only => [:new, :create, :destroy]
  get "sign_out" => "sessions#destroy", :as => "log_out"
  get "sign_in" => "sessions#new", :as => "log_in"
  
  # Static routes
  get "about" => "static#about", :as => "about"
  get "terms" => "static#tos", :as => "terms"
  
  # Password reset and recovery routes
  # get "register" => "users#new", :as => "register"
  get "register" => "signup#new", :as => "register"
  post "register" => "signup#create", :as => "signup"
	get "recovery" => "users#recovery", :as => "recovery"
	post "send_recovery" => "users#send_recovery", :as => "send_recovery"
	get "reset/:token" => "users#reset_form", :as => "reset_form"
	put "reset" => "users#reset_password", :as => "reset_password"
	get "activate/:token" => "users#activate", :as => "activate"
	
  # Newsletter subscribe path
  post "subscribe" => "static#subscribe", :as => "subscribe"
  
  # Feedback routes
  post "feedback" => "feedbacks#create", :as => "feedbacks"
  get "flag/:id" => "feedbacks#flag", :as => "flag_user"
    
  # Admin routes
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Root route
  root :to => "static#landing"
  resources :community_partner_suggestions
  
  # Catch-all route
  # If you're not logged in, then none of the routes in the constraints block
  # will be defined (Rails 404s), so if you're trying to access one of those pages,
  # this will pick up and redirect you to sign in instead of just throwing a 404.
  match '*path' => redirect('/sign_in'), via: [:get, :post], :constraints => lambda { |req| req.session[:user_id].blank? }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  belongs_to :message_thread # Added 
  validates :body, :message_thread_id, :author_id, :presence => true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @threads = current_user.message_threads.page(params[:page]).per(10).order("updated_at desc")
  end
  
  def new
    @message = Message.new
    @thread = MessageThread.new
    @user = User.find(params[:to_id]) if params[:to_id].present?
  end
  
	def create
	  if current_user.id != params[:to_id]  
  	  @message = Message.new
      @thread = MessageThread.new
      @message.update_attributes(message_params[:message])
      @thread.update_attributes(message_params[:message_thread])
      @thread.messages << @message
      current_user.messages << @message
      @thread.participancies.build(:user_id => current_user.id)
      @thread.participancies.build(:user_id => message_params[:message_thread][:to_id])
      if @thread.save && @message.save
        redirect_to messages_path, :notice => "Sent message."
      else  
        redirect_to messages_path, :notice => "Unable to send message."  
      end
    else
      redirect_to messages_path, :notice => "You can't send yourself a message."  
    end
  end 
  
  def show
    @thread = MessageThread.find(params[:id])
    @response = Message.new
    if !@thread.is_read? && @thread.messages.last.author.id != current_user.id
      @thread.is_read = true
      @thread.save!
    end

    @author = @thread.messages.first.author
  end
  
  def mark_as_read
    @thread = MessageThread.find(params[:id])
    @thread.is_read = true
    @thread.save!
    redirect_to messages_path
  end
  
  def mark_as_unread
    @thread = MessageThread.find(params[:id])
    @thread.is_read = false
    @thread.save!
    redirect_to messages_path
  end
  
  def respond
    @response = Message.new
    @thread = MessageThread.find(params[:id])
    @response.body = params[:message][:body]
    @thread.messages << @response
    current_user.messages << @response
    @thread.is_read = false
    @response.save

    @thread = MessageThread.find(params[:id])
    @response = Message.new

    @author = @thread.messages.first.author

    render :show
  end

  private

  def message_params
    params.permit!
  end
end

app/views/messages/_message.html.erb
<div class="chat-person">
  <div class="img-wrapper">
    <%#= link_to image_tag(@author.avatar_url(:thumb).to_s), user_path(@author), class: "img-fluid" %>
  </div>
  <div class="content-wrapper">
    <h4><%= @thread.subject %></h4>
  </div>
</div>
<div class="chat-detail">
  <ul id="message-box">
    <% @thread.messages.each do |msg| %>
      <% if msg.author.id == current_user.id %>
        <li class="message-item sent">
          <div class="message-content-wrapper">
            <p><%= msg.body %></p>
          </div>
        </li>
      <% else %>
        <li class="message-item received">
          <div class="message-user-avatar img-wrapper">
            <%= link_to image_tag(msg.author.avatar_url(:thumb).to_s), user_path(msg.author), class: "img-fluid" %>
          </div>
          <div class="message-content-wrapper">
            <h6><%= msg.author.name %></h6>
            <p><%= msg.body %></p>
            <h6><%= msg.created_at.strftime("%a, %b, %-d at %l:%M%P") %></h6>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="type-msg-wrapper">
  <%= form_for @response, :html => {:multipart => true}, :url => respond_message_message_path, remote: true do |f| %>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= f.text_field :body, class: "form-control", placeholder: "Type a message", required: true %>
        </div>
      </div>
      <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-paper-plane"></i></button>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="page">
  <section class="page-breadcrumb">
    <div class="container container-w80">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Message</li>
        </ol>
      </nav>
    </div>
  </section>
  <section class="page-banner">
    <div class="container container-w80">
      <div class="page-heading">
        <h2>Message</h2>
      </div>
    </div>
  </section>
  <section class="message-view">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-12">
          <div class="chat-list">
            <div class="main-heading">
            	<div class="row">
	            	<div class="col-7">
	              	<h2>Messages</h2>
	            	</div>
	            	<div class="col-5">
	              	<%= link_to "New", new_message_path, class: "btn btn-primary pull-right" %>
	            	</div>
            	</div>
            </div>
            <div class="chat-list-wrapper">
            	<% @threads.each do |thread| %>
	              <div class="chat-person">
	                <div class="img-wrapper">
	                  <%= link_to image_tag(thread.participancies.where("user_id != ?",current_user.id).first.user.avatar_url(:thumb), class: "img-fluid"), message_path(thread.id), remote: true %>
	                </div>
	                <div class="content-wrapper">
	                  <h4><%= link_to thread.participancies.where("user_id != ?",current_user.id).first.user.name, message_path(thread.id), remote: true %></h4>
	                  <p><%= thread.messages.last.body %></p>
	                </div>
	              </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 col-12">
          <div class="chat-desc" id="chat-info">
          	<div class="col-12" style="height:400px; vertical-align: middle;">
          		<h4 class="text-center" style="top: 40%; display: block; position: absolute; text-align: center;left: 30%;">Select an item to read</h4>
        		</div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/messages/new.html.erb
<div class="page">
  <section class="page-breadcrumb">
    <div class="container container-w80">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Message</li>
        </ol>
      </nav>
    </div>
  </section>
  <section class="message">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7 col-md-6 col-sm-12 col-12">
          <div class="img-wrapper">
            <%= image_tag "message-bg.png", class: "img-fluid" %>
          </div>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12 col-12">
          <div class="form-wrapper">
            <div class="main-heading">
              <h2>Send new message</h2>
            </div>
            <div class="message-form">
              <%= form_for @message, :html => {:multipart => true} do |f| %>
                <% if @message.errors.any? %>
                  <div id="error_explanation">
                    <h2>
                      <%= pluralize(@message.errors.count, "error") %> prohibited your message from being sent:</h2>
                    <ul>
                      <% @message.errors.full_messages.each do |msg| %>
                      <li>
                        <%= msg %>
                      </li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= fields_for @thread do |t| -%>
                  <div class="form-group">
                    <% if params[:to_id].present? %>
                      To: <%= link_to @user.name, @user %>
                      <%= t.hidden_field :to_id, :value => @user.id %>
                    <% else %>
                    <%= t.collection_select :to_id,
                             current_user.friends, :id, :name,
                             { include_blank: "To" },
                             class: "form-control", placeholder: "To" %>
                    <% end %>
                  </div>
                  <div class="form-group">
                    <%= t.text_field :subject, class: "form-control", placeholder: "Subject" %>
                  </div>
                <% end %>
                <div class="form-group">
                  <%= f.text_area :body, rows: 3, class: "form-control", placeholder: "Body" %>
                </div>
                <div class="main-btn text-center">
                  <%= f.button "Send Message", type: "submit", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/messages/show.html.erb
<%= link_to 'Back to messages', messages_path %>

  <h2><%= @thread.subject %></h2>
  <% @thread.messages.each do |msg| %>
  <div id="message">
      <div class="message_title">
      <%= link_to image_tag(msg.author.avatar_url(:thumb).to_s), user_path(msg.author) %>
      </div>
      <span class="message_info"><%= link_to msg.author.name, user_path(msg.author) %> on <%= msg.created_at.to_s(:pretty) %></span>
      <span class="message_body"><%= msg.body %></span><div class="clear"></div>
  </div>
  <% end %>
  <br />
  <%= form_for @response, :html => {:multipart => true}, :url => respond_message_message_path do |f| %>
	<% if @response.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@response.errors.count, "error") %> prohibited your message from being sent:</h2>

			<ul>
			<% @response.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<p>
	  Add to conversation:<br />
		<%= f.text_area :body %>
	</p>
	
	<div class="actions">
		<%= f.submit "Send Message" %>
	</div>
	<% end %>

app/views/messages/show.js.erb
$("#chat-info").html('<%= j(render("messages/message")) %>');
$("#message-box").animate({ scrollTop: $('#message-box').prop("scrollHeight")}, 10);