config/routes.rb
Roommateme::Application.routes.draw do  # 
	# Logged in
  # 
  constraints lambda { |req| !req.session[:user_id].blank? } do
    resources :users do
      resources :friends
    end    
    
    # Match route
    get 'matches' => "matches#index", :as => "matching"
    
    # Survey routes
    scope 'survey' do
      get '/' => "survey_responses#new", as: "take_survey"
      post 'submit' => "survey_responses#create", :as => "submit_survey"
      # get '/answers' => "survey_responses#show", :as => "view_survey"
    end
    
    # Messaging routes
    resources :messages, :only => [:new, :create, :show, :index] do
      get "/mark_as_read" => "messages#mark_as_read", :on => :member
      get "/mark_as_unread" => "messages#mark_as_unread", :on => :member
      get "/to/:to_id" => "messages#new", :as => "new_message", :on => :collection
		  post "/to/:to_id/create" => "messages#create", :as => "create_message", :on => :collection
		  post "/respond" => "messages#respond", :as => "respond_message", :on => :member
    end
	  
    # Search routes
    get "/search" => "search#search", :as => "search"
	  
    # Inventory routes
	  scope "/inventory" do
	    get '/' => "users#items", :as => :inventory
      get "/have/:item_id" => "users#have_item", :as => "inventory_have"
      get "/want/:item_id" => "users#want_item", :as => "inventory_want"
      delete "/have/:item_id" => "users#delete_have_item", :as => "inventory_have_delete"
      delete "/want/:item_id" => "users#delete_want_item", :as => "inventory_want_delete"
      get "/:category" => "item_categories#show", :as => :item_categories
    end
    
    # Community routes
    get "/community" => "community#index", :as => :community
    resources :affiliates, :only => [:index, :show] do
      get "/category/:category" => "affiliate_categories#show", :on => :collection, :as => :category
    end
    resources :community_partners, :only => [:index, :show] do
      get "/category/:category" => "community_partner_categories#show", :on => :collection, :as => :category
    end
    resources :tutors, :only => [:index, :show] do
      get "/category/:category" => "tutor_categories#show", :on => :collection, :as => :category
    end
    
    # Root route
	  root :to => "users#show", :as => "dashboard"
  end
  
  # browse route
  get 'browse' => "browse#index", :as => "browse"

  # 
  # Not logged in
  # 
  resources :universities, :only => [:index, :show]
  post "/users" => "users#create"
  
  # Session routes
  resources :sessions, :only => [:new, :create, :destroy]
  get "sign_out" => "sessions#destroy", :as => "log_out"
  get "sign_in" => "sessions#new", :as => "log_in"
  
  # Static routes
  get "about" => "static#about", :as => "about"
  get "terms" => "static#tos", :as => "terms"
  
  # Password reset and recovery routes
  # get "register" => "users#new", :as => "register"
  get "register" => "signup#new", :as => "register"
  post "register" => "signup#create", :as => "signup"
	get "recovery" => "users#recovery", :as => "recovery"
	post "send_recovery" => "users#send_recovery", :as => "send_recovery"
	get "reset/:token" => "users#reset_form", :as => "reset_form"
	put "reset" => "users#reset_password", :as => "reset_password"
	get "activate/:token" => "users#activate", :as => "activate"
	
  # Newsletter subscribe path
  post "subscribe" => "static#subscribe", :as => "subscribe"
  
  # Feedback routes
  post "feedback" => "feedbacks#create", :as => "feedbacks"
  get "flag/:id" => "feedbacks#flag", :as => "flag_user"
    
  # Admin routes
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  # Root route
  root :to => "static#landing"
  resources :community_partner_suggestions
  
  # Catch-all route
  # If you're not logged in, then none of the routes in the constraints block
  # will be defined (Rails 404s), so if you're trying to access one of those pages,
  # this will pick up and redirect you to sign in instead of just throwing a 404.
  match '*path' => redirect('/sign_in'), via: [:get, :post], :constraints => lambda { |req| req.session[:user_id].blank? }
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    unless params[:q] == "" or params[:q].nil?
      @users = User.search(params[:q], current_user.university.silo)
      @users_slice = @users.slice(0,10)
      @community_partners = CommunityPartner.search(params[:q], current_user.university.silo)
      @cp_slice = @community_partners.slice(0,10)
      @affiliates = Affiliate.search(params[:q])
      @aff_slice = @affiliates.slice(0,10)
      @items = Item.search(params[:q])
      @items_slice = @items.slice(0,10)
      @total_count = @users.count + @community_partners.count + @affiliates.count + @items.count
    end
  end
end

app/views/search/search.html.erb
<div class="page">
  <section class="page-breadcrumb">
    <div class="container container-w80">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Search</li>
        </ol>
      </nav>
    </div>
  </section>
  <section class="page-banner">
    <div class="container container-w80">
      <div class="page-heading">
        <h2>Search Your Best Match</h2>
        <p>This is arguably our most powerful application giving users the ability to search for others of like interest,
            tutors, and our community partners free of charge!</p>
      </div>
    </div>
  </section>
  <section class="search">
    <div class="container">
      <div class="content-wrapper">
        <div class="search-form">
          <form class="form-inline active-cyan-4">
        	<%= form_tag(search_path, :method => "get", class: "form-inline active-cyan-4") do %>
            <div class="col">
              <%= search_field_tag(:q, params[:q], :placeholder => "Search", class: "form-control form-control-sm mr-3") %>
            </div>
            <div class="col-auto">
            	<%= button_tag '<i class="fa fa-search" aria-hidden="true"></i>'.html_safe, class: "btn btn-primary", type: "submit" %>
            </div>
          <% end %>
          </form>
        </div>
      </div>
    </div>
  </section>

<% if params[:q].present? %>
  <section class="search-result">
    <div class="container container-w80">
      <div class="main-heading">
        <h2>Search Result</h2>
        <p><%= pluralize(@total_count, "result") %> found for “<%= params[:q] %>”</p>
      </div>

      <div class="search-category">
        <div class="main-heading text-left">
          <h2>Users</h2>
          <% if @users_slice.present? %>
            <p>Showing <%= @users_slice.count %> of <%= pluralize(@users.count, "user") %>.</p>
          <% else %>
            <p>No users found matching your search terms.</p>
          <% end %>
        </div>
        <div class="card-wrapper matches">
          <div class="row">
            <% @users_slice.each do |u| %>
              <div class="col-lg-2 col-md-6 col-sm-6 col-6">
                <div class="card">
                  <div class="img-wrapper">
                    <%= link_to image_tag(u.avatar_url(:big)), u, class: "img-fluid" %>
                  </div>
                  <div class="desc">
                    <h5><%= link_to u.name, user_path(u.id) unless u.nil? %></h5>
                    <p><%= u.birthtown %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="search-category search-items">
        <div class="main-heading text-left">
          <h2>Affiliates</h2>
          <% if @affiliates.present? %>
            <p>Showing <%= @aff_slice.count %> of <%= pluralize(@affiliates.count, "affiliate") %>.</p>
          <% else %>
            <p>No affiliates found matching your search terms.</p>
          <% end %>
        </div>
        <div class="card-wrapper matches">
          <div class="row">
            <% @affiliates.each do |a| %>
              <div class="col-lg-2 col-md-6 col-sm-6 col-6">
                <div class="card">
                  <div class="img-wrapper">
                      <%= link_to image_tag(a.image_url(:big), class: "img-fluid") %>
                  </div>
                  <div class="desc">
                      <h5><%= link_to a.name, affiliate_path(a.id) unless a.nil? %></h5>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="search-category search-items">
        <div class="main-heading text-left">
            <h2>Inventory items</h2>
            <% if @items.count > 0 %>
              <p>Showing <%= @items_slice.count %> of <%= pluralize(@items.count, "item") %>.</p>
            <% else %>
              <p>No inventory items found matching your search terms.</p>
            <% end %>
        </div>
        <div class="card-wrapper matches">
          <div class="row">
            <% @items.each do |a| %>
              <div class="col-lg-2 col-md-6 col-sm-6 col-6">
                <div class="card">
                  <div class="img-wrapper">
                    <%= link_to image_tag(a.image_url(:big), class: "img-fluid") %>
                  </div>
                  <div class="desc">
                    <h5><%= link_to a.name, item_categories_path(a.item_category.name) unless a.nil? %></h5>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="search-category search-items">
        <div class="main-heading text-left">
          <h2>Communtiy Partners</h2>
          <% if @community_partners.count > 0 %>
            <p>Showing <%= @cp_slice.count %> of <%= pluralize(@community_partners.count, "community partner") %>.</p>
          <% else %>
            <p>No community partners found matching your search terms.</p>
          <% end %>
        </div>
        <div class="card-wrapper matches">
          <div class="row">
            <% @community_partners.each do |c| %>
              <div class="col-lg-2 col-md-6 col-sm-6 col-6">
                <div class="card">
                  <div class="img-wrapper">
                    <%= link_to image_tag(c.image_url(:big), class: "img-fluid") %>
                  </div>
                  <div class="desc">
                    <h5><%= link_to c.name, community_partner_path(c.id) unless c.nil? %></h5>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </section>
<% end %>
</div>